// tests/durable.test.mjs — v1.1 SQLite durable store + migration tests (MY_SQLITE_WORK)
import test from 'node:test'; import assert from 'node:assert/strict';
import { mkdtempSync, existsSync, readFileSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { DurableStore } from '../src/usage/durable/durableStore.ts';
import { DurableAggregator } from '../src/usage/durable/durableAggregator.ts';
import { migrateV1Ledger, buildRecordsFromV1 } from '../src/usage/durable/migration.ts';
const DAY = (d) => d;
function rec(id, total, localDate, seq = 1, extra = {}) { const p = id.split(':'); const step = Number(p[p.length-1])||0; const turn = Number(p[p.length-2])||0; const sid = p.slice(0,-2).join(':'); return { id, source:'assistant/message', sessionId:sid||id, turn, step, seq, timestamp:Date.parse((localDate||'2026-08-16')+'T12:00:00'), localDate:localDate||'2026-08-16', inputTokens:total, outputTokens:0, cacheReadTokens:0, cacheWriteTokens:0, reasoningTokens:0, totalTokens:total, accounting:'exact', sourceType:'live_event', ...extra }; }
function tmpStore() { const dir = mkdtempSync(join(tmpdir(),'dtsd-')); return { dir, path: join(dir,'usage.db') }; }

test('durable: single upsert records global total', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('s1:1:0',1000,DAY('2026-08-16'))]); assert.equal(s.globalAggregate().total_tokens,1000); assert.equal(s.globalAggregate().calls,1); s.close(); });
test('durable: duplicate identical delivery is not double-counted', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const r = rec('x:1:0',15000,DAY('2026-08-16')); s.apply([r]); s.apply([r]); s.apply([r]); assert.equal(s.globalAggregate().total_tokens,15000); assert.equal(s.recordCount(),1); s.close(); });
test('durable: a later (higher-seq) sample REPLACES, not adds', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('s1:2:0',8000,DAY('2026-08-16'),5)]); s.apply([rec('s1:2:0',12000,DAY('2026-08-16'),9)]); assert.equal(s.globalAggregate().total_tokens,12000); assert.equal(s.globalAggregate().calls,1); assert.equal(s.recordCount(),1); s.close(); });
test('durable: older/equal seq replay ignored', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('a:1:0',500,DAY('2026-08-16'),10)]); s.apply([rec('a:1:0',300,DAY('2026-08-16'),5)]); assert.equal(s.globalAggregate().total_tokens,500); s.close(); });
test('durable: daily + model aggregates maintained', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('a:1:0',100,DAY('2026-08-16'),1,{provider:'deepseek',model:'v4'})]); s.apply([rec('b:1:0',200,DAY('2026-08-15'),1,{provider:'openai',model:'gpt'})]); assert.equal(s.daily('2026-08-16').total_tokens,100); assert.equal(s.daily('2026-08-15').total_tokens,200); assert.equal(s.modelTotals().length,2); assert.equal(s.dayModelTotals('2026-08-15').length,1); s.close(); });
test('durable: replacement adjusts all aggregate tables', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('a:1:0',100,DAY('2026-08-16'),1,{provider:'deepseek',model:'v4'})]); s.apply([rec('a:1:0',160,DAY('2026-08-16'),9,{provider:'deepseek',model:'v4'})]); assert.equal(s.globalAggregate().total_tokens,160); assert.equal(s.daily('2026-08-16').total_tokens,160); const ds=s.modelTotals().find((m)=>m.provider==='deepseek'); assert.equal(ds.total_tokens,160); assert.equal(ds.calls,1); assert.ok(s.verifyAggregates().ok); s.close(); });
test('durable: rebuildAggregates heals drift', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('a:1:0',100,DAY('2026-08-16'),1)]); s.database.exec('UPDATE aggregate_global SET total_tokens=999'); assert.equal(s.verifyAggregates().ok,false); s.rebuildAggregates(); assert.equal(s.verifyAggregates().ok,true); s.close(); });
test('durable: restart preserves totals and generation', () => { const { path } = tmpStore(); const s1 = new DurableStore({ path }); s1.apply([rec('a:1:0',11111,DAY('2026-08-16'),1)]); const gen = s1.readMeta().recordGeneration; s1.close(); const s2 = new DurableStore({ path }); assert.equal(s2.globalAggregate().total_tokens,11111); assert.equal(s2.readMeta().recordGeneration,gen); s2.close(); });
test('durable: summary Today/Yesterday/Total', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const now = ()=>Date.parse('2026-08-16T12:00:00'); s.apply([rec('a:1:0',100,DAY('2026-08-16'),1),rec('b:1:0',200,DAY('2026-08-15'),1),rec('c:1:0',300,DAY('2026-08-16'),1)]); const agg = new DurableAggregator(s,{now}); const x=agg.summary(); assert.equal(x.lifetimeTotal,600); assert.equal(x.todayTotal,400); assert.equal(x.yesterdayTotal,200); assert.equal(x.recordCount,3); agg.close(); });
test('durable: insights 7d window', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const now = Date.parse('2026-08-16T12:00:00'); s.apply([rec('a:1:0',100,DAY('2026-08-16'),1,{provider:'deepseek',model:'v4'}),rec('b:1:0',200,DAY('2026-08-14'),1,{provider:'deepseek',model:'v4'}),rec('c:1:0',999,DAY('2026-07-01'),1,{provider:'old',model:'m'})]); const agg = new DurableAggregator(s,{now:()=>now}); const d7=agg.insights('7d'); assert.equal(d7.totalTokens,300); assert.equal(d7.models.length,1); agg.close(); });
test('durable: unclassified legacy => unknown, not category/model', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('legacy:1:0',77,DAY('2026-08-16'),1,{inputTokens:0,outputTokens:0,cacheReadTokens:0,cacheWriteTokens:0,totalTokens:77})]); s.apply([rec('exact:1:0',50,DAY('2026-08-16'),1,{inputTokens:50})]); const agg = new DurableAggregator(s,{now:()=>Date.parse('2026-08-16T12:00:00')}); const all=agg.insights('all'); assert.equal(all.totalTokens,127); assert.equal(all.unknownTokens,77); assert.equal(all.categories.callCount,1); agg.close(); });

function minimalV1(records){const byId={},detailBy={},dayBy={},seqBy={},src={};let t=0;for(const r of records){byId[r.id]=r.totalTokens;t+=r.totalTokens;detailBy[r.id]={inputTokens:r.inputTokens,outputTokens:r.outputTokens,cacheReadTokens:r.cacheReadTokens,cacheWriteTokens:r.cacheWriteTokens,reasoningTokens:r.reasoningTokens,provider:r.provider,model:r.model};dayBy[r.id]=r.localDate;seqBy[r.id]=r.seq;src[r.id]=r.sourceType??'live_event';}return {lifetimeTotal:t,recordCount:records.length,byId,detailBy,dayBy,seqBy,src,schemaVersion:4};}

test('migration: empty v1 is a no-op', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const res = migrateV1Ledger(s,{v1Root:{},noBackup:true}); assert.equal(res.status,'done'); assert.equal(s.recordCount(),0); s.close(); });
test('migration: small v1 ledger totals preserved', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1,{sourceType:'live_event'}),rec('b:1:0',200,DAY('2026-08-15'),1,{sourceType:'session_log'})]); const res = migrateV1Ledger(s,{v1Root:v1,noBackup:true}); assert.equal(res.status,'done'); assert.equal(res.verification.length,0); assert.equal(s.globalAggregate().total_tokens,300); assert.equal(s.recordCount(),2); assert.equal(s.readMeta().migrationStatus,'done'); s.close(); });
test('migration: idempotent across reruns', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1),rec('b:1:0',200,DAY('2026-08-15'),1)]); migrateV1Ledger(s,{v1Root:v1,noBackup:true}); const r2=migrateV1Ledger(s,{v1Root:v1,noBackup:true}); assert.equal(r2.skippedBecauseDone,true); assert.equal(s.recordCount(),2); assert.equal(s.globalAggregate().total_tokens,300); s.close(); });
test('migration: verification failure does NOT cut over', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); s.apply([rec('existing:1:0',5000,DAY('2026-08-16'),1)]); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1)]); const res = migrateV1Ledger(s,{v1Root:v1,noBackup:true}); assert.equal(res.status,'failed'); assert.ok(res.verification.length>0); assert.equal(res.migrated,false); assert.equal(s.readMeta().migrationStatus,'failed'); assert.equal(s.recordCount(),1); s.close(); });
test('migration: crash mid-migration resumes, no dupes', () => { const { path } = tmpStore(); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1),rec('b:1:0',200,DAY('2026-08-15'),2)]); const s1 = new DurableStore({ path }); s1.apply([rec('a:1:0',100,DAY('2026-08-16'),1)]); s1.close(); const s2 = new DurableStore({ path }); const res = migrateV1Ledger(s2,{v1Root:v1,noBackup:true}); assert.equal(res.status,'done'); assert.equal(res.verification.length,0); assert.equal(s2.recordCount(),2); assert.equal(s2.globalAggregate().total_tokens,300); s2.close(); });
test('migration: live event after migration persists exactly once', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1)]); migrateV1Ledger(s,{v1Root:v1,noBackup:true}); const before = s.globalAggregate().total_tokens; s.apply([rec('live:1:0',14174,DAY('2026-08-16'),1)]); assert.equal(s.globalAggregate().total_tokens,before+14174); assert.equal(s.recordCount(),2); s.close(); });
test('migration: preserves provider/model and local_date', () => { const { path } = tmpStore(); const s = new DurableStore({ path }); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1,{provider:'anthropic',model:'claude'})]); migrateV1Ledger(s,{v1Root:v1,noBackup:true}); const dm = s.dayModelTotals('2026-08-16'); assert.equal(dm.length,1); assert.equal(dm[0].provider,'anthropic'); s.close(); });
test('migration: backup written, v1 source untouched', () => { const { path } = tmpStore(); const dir = mkdtempSync(join(tmpdir(),'dtsb-')); const v1Path = join(dir,'dsh_token_usage_sidebar.json'); const v1 = minimalV1([rec('a:1:0',100,DAY('2026-08-16'),1)]); writeFileSync(v1Path, JSON.stringify({ unit:{name:'dsh_token_usage_sidebar',version:1}, global:null, tables:{ ledger:{ root: v1 } } })); const s = new DurableStore({ path }); const res = migrateV1Ledger(s,{v1Path,backupDir:dir}); assert.equal(res.status,'done'); assert.ok(res.backupPath); assert.ok(existsSync(res.backupPath)); assert.equal(JSON.parse(readFileSync(v1Path,'utf8')).tables.ledger.root.lifetimeTotal,100); assert.equal(readFileSync(res.backupPath,'utf8'),readFileSync(v1Path,'utf8')); s.close(); });
test('migration: canonical id maps back to sessionId:turn:step', () => { const v1 = { lifetimeTotal:10, recordCount:1, byId:{'session-x:3:4':10}, dayBy:{'session-x:3:4':'2026-08-16'}, detailBy:{'session-x:3:4':{inputTokens:10,outputTokens:0,cacheReadTokens:0,cacheWriteTokens:0,reasoningTokens:0}} }; const recs = buildRecordsFromV1(v1); assert.equal(recs[0].id,'session-x:3:4'); assert.equal(recs[0].sessionId,'session-x'); assert.equal(recs[0].turn,3); assert.equal(recs[0].step,4); assert.equal(recs[0].localDate,'2026-08-16'); });
